version: '3.3'
services:
  caddy:
      image: caddy:2-alpine
      restart: always
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./public:/public
        - caddy:/data
        - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy: {}