name: blog
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
region: fra
static_sites:
 - build_command: hugo mod get; rm -r ./public; hugo --destination ./public
   environment_slug: hugo
   github:
     branch: trunk
     deploy_on_push: true
     repo: kbetanski/blog
   name: blog
   envs:
    - key: HUGO_VERSION
      value: "0.96.0"
      scope: BUILD_TIME
      type: GENERAL
    - key: HUGO_EXTENDED
      value: "1"
      scope: BUILD_TIME
      type: GENERAL
